### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by TWINGSISTER** [abinpaul1/GPS-Video-Logger#3]
The first two releases do not install ADB says [INSTALL_PARSE_FAILED_NO_CERTIFICATES].
Latest install on 4.4.2 but do not run. No idea what log to post here. It is a really interesting recorder for bike! Hope to see it work.

**Comment by abinpaul1** [comment]
Would you be able to provide the output of 
```
adb logcat | grep com.example.gps_app
``` 
when trying to run the app on Android 4.4.2 after installing.

**Comment by TWINGSISTER** [comment]
Many thanks for your prompt reply!
I wasn't able to answer to you  so quickly!
Now I am using a crappy mediatek china tablet with Android 4.4.2. and a totally misconfigured memory map (cannot install too many app and I have plenty of space for videos!)
At home I have a desktop running W10 and I never developed for Amdroid, I have sone experience with Eclipse with Python and also Javascript.
I am interested in your app for this http://primi235711.altervista.org/moodle/course/view.php?id=21 (log in as guest).
You will find in attachment the result of

adb logcat>foo.txt

I think that the problem is with the camera. Other apps on that device report problem with connecting with the camera and upon several retry, in the end, they succeed. 
Here are the lines in foo.txt attached 
1839: E/AndroidRuntime( 2573): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.gps_app/com.example.gps_video_logger.Recording}: java.lang.NullPointerException

27859: W/System.err( 2652): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.gps_app/com.example.gps_video_logger.Recording}: java.lang.NullPointerException


27951: E/AndroidRuntime( 2652): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.gps_app/com.example.gps_video_logger.Recording}: java.lang.NullPointerException

If you find this interesting I suggest to add some hints  on how to start a development environment in W10 using Eclipse.
I can experiment with this and upload to this repo the eclipse project so that others can import this directly into Eclipse.

From the app point of view I suggest that this app should work   without video as a gpx file recorder. 
In the meanwhile I will see if there is some way to convince this app that there actually is a camera on this device...


[res.txt](https://github.com/abinpaul1/GPS-Video-Logger/files/6828533/res.txt)
[foo.txt](https://github.com/abinpaul1/GPS-Video-Logger/files/6828540/foo.txt)

**Comment by abinpaul1** [comment]
Thanks for providing the log file. You' re right, it does seem to be a problem with the camera. I'll try to attempt a fix, however I don't have an Android 4.4 device to test on. I was planning to for a minimum requirement of Android 5 as well, so I can't guarantee a fix.

If your project only requires recording GPS coordinates into a GPX file, I would recommend looking at [GPSLoggger](https://github.com/mendhak/gpslogger/). It's a well maintained project.

This project was done in Android Studio. As such porting it to Eclipse would be quite time consuming. If you are interested in developing for Android, I would recommed setting up Android Studio for the same.

**Comment by TWINGSISTER** [comment]
Thanks! will give the fix a try and will report. Let me add that I am delighted by the incredible speed with which you provide support. Yes I can go for two separate apps one for video and one for gpx. The possible delay in sync, when coming to cycling, is not an issue. Yet I always try K.I.S.S. first so..

**Comment by abinpaul1** [comment]
[app-debug.zip](https://github.com/abinpaul1/GPS-Video-Logger/files/7112182/app-debug.zip)
Its been a while. If you are still interested, can you please try running this debug apk and provide the logs as well.

**Comment by abinpaul1** [comment]
Closing for now. Feel free to reopen as required
